name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      working-directory: todo-back
      run: composer validate --strict

    - name: Cache Composer packages
      uses: actions/cache@v3
      with:
        path: todo-back/vendor
        key: ${{ runner.os }}-php-${{ hashFiles('todo-back/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      working-directory: todo-back
      run: composer install --prefer-dist --no-progress

    # - name: Run test suite
    #   working-directory: todo-back
    #   run: composer run-script test
